### ISSUE TITLE
Gonsole does not work

### ISSUE THREAD

**Issue by OmarAlghamdi** [rherrmann/gonsole#76] opened 2018-06-21 01:47 UTC
I installed this plugin but when I try launch it nothing happens
I am using Eclipse IDE for Java Developers
Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200

I installed the plugin from eclipse marketplace

**Comment by fappel** [comment] 2018-06-21 05:13
Thanks for trying out gonsole. Could you please check the Eclipse error log to see if there are any entries that could help us to understand what's going wrong?

**Comment by xBioHazx** [comment] 2018-11-06 09:59
I get this error (among others):
Failed to execute item com.codeaffine.gonsole.internal.command.ShowInGitConsole
org.eclipse.e4.core.di.InjectionException: java.nio.file.InvalidPathException: Illegal char <:> at index 54: /home/magnus/workspace-xxxx/XxxxxXxxxxxCoreCommon/.git:/home/magnus/workspace-xxxx/DevXxxxxXxxxxx/.git:/home/magnus/workspace-xxxx/xxxxXxxxxXxxxxxCommon/.git:/home/magnus/workspace-xxxx/eclipse-ant/.git:/home/magnus/workspace-xxxx/xxxxXxxxxXxxxxx/.git:/home/magnus/workspace-xxxx/resin/.git:/home/magnus/workspace-xxxx/launchers/.git:/home/magnus/workspace-xxxx/DevXxxxxXxxxxxCommon/.git:/home/magnus/workspace-xxxx/XxxxxXxxxxxCore/.git:/home/magnus/workspace-xxxx/xxxxxxcore/.git:/home/magnus/workspace-xxxx/xxxxCommon/.git:
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:207)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:399)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:824)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:801)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.crexxxxndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.crexxxxndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.crexxxxndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 54: /home/magnus/workspace-xxxx/XxxxxXxxxxxCoreCommon/.git:/home/magnus/workspace-xxxx/DevXxxxxXxxxxx/.git:/home/magnus/workspace-xxxx/xxxxXxxxxXxxxxxCommon/.git:/home/magnus/workspace-xxxx/eclipse-ant/.git:/home/magnus/workspace-xxxx/xxxxXxxxxXxxxxx/.git:/home/magnus/workspace-xxxx/resin/.git:/home/magnus/workspace-xxxx/launchers/.git:/home/magnus/workspace-xxxx/DevXxxxxXxxxxxCommon/.git:/home/magnus/workspace-xxxx/XxxxxXxxxxxCore/.git:/home/magnus/workspace-xxxx/xxxxxxcore/.git:/home/magnus/workspace-xxxx/xxxxCommon/.git:
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at sun.nio.fs.AbstractPath.resolve(Unknown Source)
	at org.eclipse.egit.core.RepositoryUtil.toDirSet(RepositoryUtil.java:457)
	at org.eclipse.egit.core.RepositoryUtil.migrxxxxbolutePaths(RepositoryUtil.java:437)
	at org.eclipse.egit.core.RepositoryUtil.getRepositories(RepositoryUtil.java:418)
	at org.eclipse.egit.core.RepositoryUtil.getConfiguredRepositories(RepositoryUtil.java:467)
	at com.codeaffine.gonsole.egit.internal.EGitFacade.getConfiguredRepositories(EGitFacade.java:26)
	at com.codeaffine.gonsole.egit.internal.EGitFacade.getConfiguredRepositoryLocations(EGitFacade.java:22)
	at com.codeaffine.gonsole.egit.internal.repositores.EGitRepositoryProvider.getRepositoryLocations(EGitRepositoryProvider.java:14)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProvider.stream(CompositeRepositoryProvider.java:60)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProvider.lambda$0(CompositeRepositoryProvider.java:28)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProvider.getRepositoryLocations(CompositeRepositoryProvider.java:29)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProviderFactory.updateCurrentRepositoryLocation(CompositeRepositoryProviderFactory.java:27)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProviderFactory.create(CompositeRepositoryProviderFactory.java:22)
	at com.codeaffine.gonsole.GitConsoleFactory.createCompositeRepositoryProvider(GitConsoleFactory.java:32)
	at com.codeaffine.gonsole.GitConsoleFactory.getConsoleConfigurer(GitConsoleFactory.java:27)
	at com.codeaffine.console.core.ConsoleFactory.createConsole(ConsoleFactory.java:30)
	at com.codeaffine.console.core.ConsoleFactory.openConsole(ConsoleFactory.java:24)
	at com.codeaffine.gonsole.internal.command.ShowInGitConsoleHandler.openConsole(ShowInGitConsoleHandler.java:43)
	at com.codeaffine.gonsole.internal.command.ShowInGitConsoleHandler.execute(ShowInGitConsoleHandler.java:26)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 36 more

**Comment by rherrmann** [comment] 2018-11-06 11:41
@xBioHazx, with the little information given, I can only guess: In its preferences, EGit keeps a list of paths to configured repositories. Individual path entries are separated with the path separator char of the current platform (i.e. `:` on Unix, `;` on Windows). 

Gonsole uses this list to match the underlying path of the selection with a _known_ repository.

The error you see suggests that you have copied preferences from a computer running Unix to Windows. 

If this doesn't help, please provide more context, e.g. which OS, which version of Gonsole, which version of EGit, what are the exact steps to see the problem, and everything else you can think of which would make reproducing the problem for us as straight-forward as possible.

**Comment by xBioHazx** [comment] 2018-11-06 14:46
Thanks! I did migrate from unix to Windows a long time ago and apparently there were old entries in the config. Solved after doing what's suggested here: 
https://stackoverflow.com/questions/22310939/how-to-reconfigure-eclipse-egit-after-move-from-linux-to-windows

**Comment by rherrmann** [comment] 2018-11-06 15:52
As the reporter's who hijacked this issue seems happy and the original poster also didn't respond, I'll close this issue.

**Closed by rherrmann** 2018-11-06 15:52 UTC
