### ISSUE TITLE
Not working in my Eclipse luna v 4.4

### ISSUE THREAD

**Issue by jdariasl80** [rherrmann/gonsole#71] opened 2017-05-26 14:21 UTC
Installed in eclipse luna but not showing the Gonsole in the menu

# Plugin installed
<img width="491" alt="xwin_2017-05-26_09-17-16" src="https://cloud.githubusercontent.com/assets/10852579/26498315/3f7b1020-41f4-11e7-9384-854858f202fe.png">

# Console menu
<img width="960" alt="xwin_2017-05-26_09-18-22" src="https://cloud.githubusercontent.com/assets/10852579/26498326/4ce677fe-41f4-11e7-8c6a-63d0b496e885.png">

# Eclipse version
<img width="960" alt="2017-05-26_09-19-44" src="https://cloud.githubusercontent.com/assets/10852579/26498389/84f59d96-41f4-11e7-8075-4b87b855b238.png">

Any other thing to do to make it work?

Thank you.

**Comment by rherrmann** [comment] 2017-05-28 07:55
Note that Gonsole requires running Eclipse on Java 1.8 or newer (see the requirements section on http://rherrmann.github.io/gonsole/).

Make sure that a compatible Java Version, is used to run Eclipse. Look for the `java.version` environment setting _Help_ > _About_ >_Installation Details_ > _Configuration_ Also, check if there are any related log entries in the _Error log_ view.

**Comment by rherrmann** [comment] 2017-06-01 11:01
Closing as duplicate of #66
@jdariasl80 please reopen if you still experience problems.

**Closed by rherrmann** 2017-06-01 11:01 UTC
